spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/lovegosa
#    url: jdbc:mariadb://localhost:3306/lovegosa?serverTimezone=KST&createDatabaseIfNotExist=false&autoReconnect=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: wkd
    password: wkd
  sql:
    init:
      platform: mariadb
  jpa:
#    properties:
    hibernate:
      ddl-auto: create
      show_sql: true
      format_sql: true
      use_sql_comments: true
      dialect: org.hibernate.dialect.MariaDBDialect